The Little Clojurian

* The Ten Commandments
** The First Commandment
   When Recurring on a list of atoms, /lat/, ask two questions about it:
   (null? lat) and /else/.
   
   When recurring on a number, /n/, ask two questions about it:
   (zero? n) and /else/.

   When recurring on a list of S-expressions, /l/, ask three questions about it:
   (null? l), (atom? (car l)), and /else/.
** The Second Commandment
   Use /cons/ to build lists
** The Third Commandment
   When building a list, describe the first typical element, and then /cons/ it
   onto the natural recursion.
** The Fourth Commandment
*** Always change at least one argument while recurring.
**** When recurring on a list of atoms /lat/ use (cdr lat).
**** When Recurring on a number, /n/, use (sub1 n).
**** When recurring on a list of S-expressions, /l/, use (car l) and (cdr l), if neither (null? l) not (atom? (car l)) are true.
*** It must be changed to be closer to termination. The changing argument must be tested in the termination condition:
**** when using /cdr/, test termination with /null?/ 
**** when using /sub1/, test termination with /zero?/
** The Fifth Commandment
*** When Building a value with /+/, always use 0 for the value of the terminating line, for adding 0 does not change the value of an addition.
*** When building a value with /x/, always use 1 for the value of the terminating line, for multiplying by 1 does not change the value of a multiplication.
*** When building a value with /cons/, always consider () for the value of the terminating line.
** The Sixth Commandment
Simplify only after the function is correct.
** The Seventh Commandment
Recur on the /subparts/ that are of the same nature:
- On the subparts of a list.
- On the subexpressions of an arithmetic expression.
** The Eigth Commandment
Use helpful functions to abstract from representations.
** The Ninth Commandment
Abstract common patterns with a new function.
** The Tenth Commandment
Build functions to collect more than one value at a time.
* The Five Rules
** The Law of Car
The primitive car is defined only for non-empty lists.
** The Law of Cdr
The primitive cdr is defined only for non-empty lists. The cdr of any non-empty
list is always another list.
** The Law of Cons
The primitive cons takes two arguments.
The second argument to cons must be a list.
The result is a list.
** The Law of Null?
The primitive null? is defined only for lists.
** The Law of Eq?
The primitive eq? takes two arguments. Each must be a non-numeric atom.
* 1. Toys
** What is an atom?
*** (hint, not a seq)
#+BEGIN_SRC clojure :session
(def atom? 
  (fn [x] 
    (not (seq? x))))
#+END_SRC
#+RESULTS:
: #'user/atom?
*** what about a string?
#+BEGIN_SRC clojure :session
(atom? "string")
#+END_SRC
*** what about a number?
#+BEGIN_SRC clojure :session
(atom? 1337)
#+END_SRC
*** what about a keyword?
#+BEGIN_SRC clojure :session
(atom? :keywords)
#+END_SRC
** What is a list?
*** hint, not an atom!
*** an atom enclosed by parentheses
#+BEGIN_SRC clojure :session
(list? ("string"))
#+END_SRC
*** what if a ' precedes the open paren?
#+BEGIN_SRC clojure :session
(list? '("string"))
#+END_SRC
*** can lists nest?
#+BEGIN_SRC clojure :session
(list? '((one) two (((three)))))
#+END_SRC
** What is an symbolic expression?
*** (hint, lists are flexible)
#+BEGIN_SRC clojure :session
(def sexp?
  (fn [x]
    (or (seq? x) (atom? x))))
#+END_SRC
#+RESULTS:
: #'user/sexp?
*** an atom?
#+BEGIN_SRC clojure :session
(sexp? "string")
#+END_SRC
*** an empty list?
#+BEGIN_SRC clojure :session
(sexp? '("string"))
#+END_SRC
** Baby you can drive my car
*** what is the first of (a b c)?
#+BEGIN_SRC clojure
  (first '(a b c))
#+END_SRC
*** What is the first of the first of ((a b) c)?
#+BEGIN_SRC clojure :session
(first (first '((a b) c)))
#+END_SRC
*** What is the first of an empty list?
#+BEGIN_SRC clojure :session
(first '())
#+END_SRC
*** The first rule is the law of car!
** cdr? I barely know her
*** what is the rest of (a b c)?
#+BEGIN_SRC clojure :session
(rest '(a b c))
#+END_SRC
*** what is the rest of the first of ((a b) c (d))?
#+BEGIN_SRC clojure :session
(rest (first '((a b) c (d))))
#+END_SRC
*** what is the rest of a?
#+BEGIN_SRC clojure :session
(rest 'a)
#+END_SRC
*** The second rule is the law of cdr!
** cons
*** What is the cons of the atom "peanut" and the list ("butter" "and" "jelly)?
#+BEGIN_SRC clojure :session
(cons "peanut" '("butter" "and" "jelly"))
#+END_SRC
*** 
** true
** or false
** or null
* 2. Do it, Do it Again, and Again, and Again...
* 3. Cons the Magnificent)
* 4. Numbers Games
* 5. *Oh my God*: It's Full of Stars
* 6. Shadows
* 7. Friends and Relations
* 8. Lambda the Ultimate
* 9. ...and Again, and Again, and Again, ...
* 10. What is the Value of All This?
* Intermission
* Index
